[package]
name = "ytgrab"
version = "1.0.0"
description = "YouTube Downloader — MP3, MP4, any quality"
authors = ["Micael San Pedro"]
edition = "2021"

[lib]
name = "ytgrab_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
percent-encoding = "2"
regex-lite = "0.1"
